### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by joshclancy** [koulanurag/visTorch#2]
Hello, I'm attempting to get your code running for my personal VAE project. Thanks for putting it up! 

I'm running into an issue with getting it to import autoencoder from components. Personally I'm not great at handling dependencies, so this might be me. But I believe I have installed everything that is needed.

`~\AppData\Roaming\Python\Python37\site-packages\vistorch-0.0.1-py3.7.egg\visTorch\core.py in 
      4 import dash_html_components as html
      5 import dash_bootstrap_components as dbc
----> 6 from visTorch.components import autoencoder
      7 
      8 

ModuleNotFoundError: No module named 'visTorch.components'`

Any ideas on what may be causing this issue???

**Comment by koulanurag** [comment]
Hi @joshclancy,
Thanks for bringing it to my notice. I guess the issue was due to a mismatch between the new torchvision version (0.5.0) and the older PyTorch version (1.0.1).

I have updated the dependencies to use the older torchvision for compatibility.
